FROM deepfabric/centos

RUN yum -y install go \
    && yum -y install make \
    && go get github.com/funny/slab \
    && go get github.com/deepfabric/c-nemo \
    && go get github.com/deepfabric/go-nemo 
   